version: '3.8'

services:
  db:
    image: postgres:13
    container_name: sales_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword  # รหัสผ่าน
      POSTGRES_DB: sales_db                # ชื่อ Database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: